apiVersion: v1
kind: Service
metadata:
  name: animea-animes
spec:
  selector:
    app: animea-animes
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31000
  type: NodePort